version 3.0
services:
  s3Reader:
    container_name: "jsonReaderWill"
    image:
    environment:
      - ACCESS_KEY_ID: $aws_access_key_id
      - SECRET_ACCESS_KEY: $aws_secret_access_key
      - FILE_ID: $FILE_ID