AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    a6b671b7-d2c2-4d79-a58d-d7c65b8417ef:
      size:
        width: 60
        height: 60
      position:
        x: 660
        'y': 180
      z: 1
      embeds: []
    dd4d8a24-07ae-48c7-8934-ce09ec997543:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 180
      z: 1
      embeds: []
    91cb96a1-cdba-4270-b623-857a0412e3b4:
      size:
        width: 60
        height: 60
      position:
        x: 750
        'y': 180
      z: 1
      embeds: []
    1d5e977d-b34f-41da-bd7e-91d2389c444c:
      size:
        width: 60
        height: 60
      position:
        x: 900
        'y': 180
      z: 1
      embeds: []
    179010f3-9d1b-49ce-ad13-0f044feb059e:
      size:
        width: 60
        height: 60
      position:
        x: 820
        'y': 180
      z: 1
      embeds: []
Resources:
  ecrreviewer:
    Type: 'AWS::IAM::User'
    Properties:
      Path: /ecrreviewer/
      UserName: ecrreviewer
      Policies:
        - PolicyName: ecr_test_access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 'ecr:GetAuthorizationToken'
                Resource:
                  - 'arn:aws:s3:::fiftheyeecrtest/*'
                  - '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dd4d8a24-07ae-48c7-8934-ce09ec997543
  ecraccesskey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      Status: Active
      UserName: !Ref ecrreviewer
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a6b671b7-d2c2-4d79-a58d-d7c65b8417ef
  ecrCredentialsStored:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'ecrrievewer/credntials'
      SecretString: !Sub >-
        {"ACCESS_KEY":"${ecraccesskey}","SECRET_KEY":"${ecraccesskey.SecretAccessKey}"}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 179010f3-9d1b-49ce-ad13-0f044feb059e
  fiftheyeecrtest:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'fiftheyeecrtest'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 91cb96a1-cdba-4270-b623-857a0412e3b4
  ecrjsontest:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: ecrjsontest
      ImageTagMutability: MUTABLE
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1d5e977d-b34f-41da-bd7e-91d2389c444c