# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  python: circleci/python@2.0.2
  aws-ecr: circleci/aws-ecr@7.3.0



jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ./python
          pip-dependency-file: requirements.txt 
      - run:
          name: Run tests
          command:
            aws configure set aws_access_key_id ACCESS_KEY_ID
            aws configure set aws_secret_access_key SECRET_ACCESS_KEY
            aws configure set default.region AWS_REGION
            python3 ./python/s3reader.py


workflows:
  build_and_push: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          context: myContext
          create-repo: false
          dockerfile: DockerFile
          no-output-timeout: 20m
          path: ./docker
          profile-name: PROFILE
          region: AWS_REGION
          repo: ecrjsontest
          requires:
            - build-and-test
          filters:
            branches:
              only: main
